Repository exasol/virtual-schemas, pull requests merged in 2019-06, with the labels that each got.

#193 Feature/189 big query adapter
  README.md
  doc/development/step_by_step_guide_to_writing_your_own_dialect.md
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  doc/user-guide/dialects/db2.md
  doc/user-guide/dialects/exasol.md
  doc/user-guide/dialects/hive.md
  doc/user-guide/dialects/impala.md
  doc/user-guide/dialects/oracle.md
  doc/user-guide/dialects/postgresql.md
  doc/user-guide/dialects/redshift.md
  doc/user-guide/dialects/sql_server.md
  doc/user-guide/dialects/sybase.md
  doc/user-guide/dialects/teradata.md
  doc/user-guide/user_guide.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/athena/AthenaSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/generic/GenericSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/redshift/RedshiftSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapterFactory.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/resources/sql_dialects.properties
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/DummySqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/athena/AthenaSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriterTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialectTest.java
Labels: feature

#204 #189: Fixed `NULL` handling.
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriterTest.java
Labels: bug

#202 #201: fixed 'order by' clause problems
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriterTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java
Labels: bug

#206 Bugfix/196 reenable kerberos in import
  README.md
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseConnectionDefinitionBuilder.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/KerberosUtils.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/RemoteConnectionFactory.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/auth/kerberos/KerberosConfigurationCreator.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/auth/kerberos/KerberosConfigurationCreatorException.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/SqlDialectRegistryTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/DummyRemoteMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/RemoteConnectionFactoryTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/auth/kerberos/KerberosConfigurationCreatorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/logging/CompactFormatterTest.java
Labels: bug

#208 #207: implemented getAdapterVersion()
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapterFactory.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterFactoryTest.java
Labels: feature

#209 Bug/115 drop virtual schema with misconfigured output
  README.md
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/launch/virtual-schemas version.sh unify.launch
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/logging/CapturingLogHandler.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/logging/CompactFormatterTest.java
Labels: enhancement

#215 #214: Upgrade dependency to `virtual-schema-common-java` 7.0.0
  jdbc-adapter/pom.xml
Labels: refactoring

#216 #213: removed unsupported data types
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java
Labels: bug

#219 enhancement/217_Documented file exclusion patterns for code duplication checking
  doc/development/developing_a_dialect.md
  doc/development/static_code_analysis.md
  jdbc-adapter/virtualschema-jdbc-adapter/.settings/org.eclipse.jdt.core.prefs
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterTest.java
Labels: enhancement

#221 #220: Removed redis demo adapter.
  python-redis-demo-adapter/README.md
  python-redis-demo-adapter/python-redis-adapter.sql
Labels: enhancement

#211 Feature/205 sap hana sql dialect
  README.md
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  doc/user-guide/user_guide.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/athena/AthenaSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/saphana/SapHanaMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/saphana/SapHanaSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapterFactory.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/resources/sql_dialects.properties
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/saphana/SapHanaMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/saphana/SapHanaSqlDialectTest.java
Labels: feature

#222 #212: BucketFS port might be different
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
Labels: bug

#224 Enhancement/69 update dependencies
  README.md
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
Labels: enhancement
