Repository exasol/virtual-schemas, pull requests merged in 2019-08, with the labels that each got.

#230 Bugs/229 improve sonar cloud results
  .travis.yml
  jdbc-adapter/virtualschema-jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/BaseQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitorException.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/exasol/ExasolQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/redshift/RedshiftSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/sql/SqlConstants.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/CustomSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/FileBasedIntegrationTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/SqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/VisitorAssertions.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/db2/DB2SqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/teradata/TeradataSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/utils/SqlNodesCreator.java
Labels: bug

#245 #234: converting all oracle timestamp into timestamp format in Exasol
  doc/dialects/oracle.md
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/BaseQueryRewriter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/ResultSetMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractIntegrationTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/db2/DB2SqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterTest.java
Labels: bug

#246 Feature/241 improve handling of binary types in oracle dialect
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/.settings/org.eclipse.jdt.core.prefs
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapter.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractIntegrationTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/db2/DB2SqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/teradata/TeradataSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java
Labels: feature

#248 #247: ported to Java 9 and removed guava dependencies
  .travis.yml
  jdbc-adapter/integration-test-data/run_integration_tests.sh
  jdbc-adapter/launch/virtual-schema clean package.launch
  jdbc-adapter/launch/virtual-schema clean.launch
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter-dist/.settings/org.eclipse.core.resources.prefs
  jdbc-adapter/virtualschema-jdbc-adapter-dist/.settings/org.eclipse.jdt.core.prefs
  jdbc-adapter/virtualschema-jdbc-adapter/.settings/org.eclipse.jdt.core.prefs
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/CustomSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/DialectTestData.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/SqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialectIT.java
Labels: refactoring

#253 Feature/249 improve clob handling in oracle dialect
  doc/dialects/oracle.md
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitorTest.java
Labels: feature
