Repository exasol/virtual-schemas, pull requests merged in 2019-09, with the labels that each got.

#255 #252: Handling unsupported column in `SELECT *`
  jdbc-adapter/launch/virtual-schema debug listen on port 8000.launch
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/ResultSetMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectFactoryTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/ResultSetMetadataReaderTest.java
Labels: bug

#256 #176: add decimal format cast in Hive
  doc/dialects/hive.md
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveProperties.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseColumnMetadataReaderTest.java
Labels: feature

#259 #258: fixed wildcards in imports
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlGenerationHelper.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleTableMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/redshift/RedshiftSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/saphana/SapHanaMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitor.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapterFactory.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/BaseConnectionDefinitionBuilderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/CustomSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/PostgreSQLIdentifierMappingTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/SqlGenerationHelperTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/VisitorAssertions.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveSqlDialectIT.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/hive/HiveSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseColumnMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterFactoryTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/SchemaAdapterNotesJsonConverterTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/SchemaAdapterNotesTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/utils/SqlNodesCreator.java
Labels: refactoring

#268 #267: added MySQL catalog support
  README.md
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/mysql.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  doc/user-guide/user_guide.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectTest.java
Labels: bug
