Repository exasol/virtual-schemas, pull requests merged in 2019-07, with the labels that each got.

#227 #139: implemented missing capabilities for Impala dialect
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialectTest.java
Labels: enhancement

#228 #157: initialized all dialect capabilities using one pattern
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/db2/DB2SqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/generic/GenericSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/redshift/RedshiftSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialect.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/db2/DB2SqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/redshift/RedshiftSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialectTest.java
Labels: enhancement

#232 #67: Port tests to JUnit5
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/CustomSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/FileBasedIntegrationTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/saphana/SapHanaMetadataReaderTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/saphana/SapHanaSqlDialectTest.java
Labels: refactoring

#225 #86: refactored SqlTestUtil
  doc/dialects/athena.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/CustomSqlGenerationVisitorTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/SqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlDialectTest.java
  jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/sql/SqlNormalizer.java
Labels: bug

#236 Feature/235 add documentation about connecting to aurora
  .travis.yml
  README.md
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/exasol.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/deploying_the_virtual_schema_adapter.md
  doc/user-guide/sql_clients.md
  doc/user-guide/user_guide.md
  jdbc-adapter/integration-test-data/integration-test-db2.yaml
  jdbc-adapter/integration-test-data/integration-test-sample.yaml
  jdbc-adapter/integration-test-data/integration-test-travis.yaml
  jdbc-adapter/local/integration-test-config.yaml
  jdbc-adapter/pom.xml
Labels: feature
