Repository exasol/virtual-schemas, pull requests merged in 2020-12, with the labels that each got.

#406 * #402: Updated the documentation about implementing a new dialect.
  doc/changes/changelog.md
  doc/changes/changes_4.0.5.md
  doc/development/developing-sql-dialect/developing_a_dialect.md
  doc/development/developing-sql-dialect/implementing_additional_dialect_specific_behavior.md
  doc/development/developing-sql-dialect/implementing_mandatory_sql_dialect_classes.md
  doc/development/developing-sql-dialect/integration_testing_with_containers.md
Labels: documentation

#429 * #427: Excluded transitive `org.apache.httpcomponents:httpclient` de…
  doc/changes/changes_4.0.5.md
  pom.xml
Labels: bug

#434 Enable `JOIN` capabilities in `MySQL` dialect adapter
  doc/changes/changes_4.0.5.md
  src/main/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialect.java
  src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectTest.java
Labels: feature
