Repository exasol/virtual-schemas, pull requests merged in 2020-08, with the labels that each got.

#361 Updated documentation
  .github/workflows/upload_release_asset.yml
  README.md
  doc/changes/changelog.md
  doc/changes/changes-4.0.3.md
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/mysql.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/user_guide.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
  src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectIT.java
Labels: documentation

#366 Bugs/367 oracle dialect decimal invalid precision bug
  README.md
  doc/changes/changes-4.0.3.md
  doc/dialects/oracle.md
  doc/user-guide/dialects.md
  doc/user-guide/user_guide.md
  src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
  src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
  src/test/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReaderTest.java
  src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialectIT.java
Labels: bug

#368 #283: tested new SQL Server driver, added integration test, updated S…
  README.md
  doc/changes/changes-4.0.3.md
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/mysql.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/user_guide.md
  pom.xml
  src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerColumnMetadataReader.java
  src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitor.java
  src/test/java/com/exasol/adapter/dialects/AbstractIntegrationTest.java
  src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
  src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerColumnMetadataReaderTest.java
  src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitorTest.java
  src/test/resources/container-license-acceptance.txt
  src/test/resources/integration/driver/sqlserver/mssql-jdbc-8.4.0.jre8.jar
  src/test/resources/integration/driver/sqlserver/settings.cfg
  src/test/resources/integration/driver/sqlserver/sqlserver.properties
Labels: refactoring

#372 #371: Added data types conversion for Hive dialect
  .github/workflows/upload_release_asset.yml
  doc/changes/changelog.md
  doc/changes/changes_4.0.1.md
  doc/changes/changes_4.0.2.md
  doc/changes/changes_4.0.3.md
  doc/changes/changes_4.0.4.md
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/mysql.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  doc/user-guide/user_guide.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
Labels: documentation

#376 Added links to BucketFS documentation.
  doc/user-guide/user_guide.md
Labels: documentation
