Repository exasol/virtual-schemas, pull requests merged in 2020-09, with the labels that each got.

#385 #354: Adapter notes must be strings
  doc/development/api/virtual_schema_api.md
Labels: bug, documentation

#382 #377: improved API documentation about scalar functions
  doc/changes/changes_4.0.4.md
  doc/development/api/capabilities_list.md
  doc/development/api/scalar_functions_api.md
  doc/development/api/virtual_schema_api.md
Labels: documentation

#387 #386: removed the documentation that was moved to the portal. Added l…
  README.md
  doc/changes/changes_4.0.4.md
  doc/user-guide/sql_clients.md
  doc/user-guide/unrecognized_and_unsupported_data_types.md
  doc/user-guide/user_guide.md
  doc/user-guide/virtual_schema_properties.md
Labels: documentation

#392 Added Exasol 7 to the list of supported versions
  README.md
Labels: documentation

#393 #389: Improved connection error handling.
  doc/changes/changes_4.0.4.md
  src/main/java/com/exasol/adapter/dialects/athena/AthenaSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialect.java
  src/main/java/com/exasol/adapter/dialects/db2/DB2SqlDialect.java
  src/main/java/com/exasol/adapter/dialects/generic/GenericSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/redshift/RedshiftSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/saphana/SapHanaSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialect.java
  src/test/java/com/exasol/adapter/dialects/dummy/DummySqlDialect.java
Labels: refactoring

#395 #394: Described 'No suitable driver found', added a note that Hive 1.…
  README.md
  doc/changes/changes_4.0.4.md
  doc/dialects/hive.md
  doc/user-guide/troubleshooting.md
Labels: documentation

#397 * #396: Updated to the `virtual-schema-common-java:6.0.0`
  .github/workflows/github_release.yml
  README.md
  doc/changes/changes_4.0.4.md
  doc/dialects/athena.md
  doc/dialects/aurora.md
  doc/dialects/bigquery.md
  doc/dialects/db2.md
  doc/dialects/hive.md
  doc/dialects/impala.md
  doc/dialects/mysql.md
  doc/dialects/oracle.md
  doc/dialects/postgresql.md
  doc/dialects/redshift.md
  doc/dialects/saphana.md
  doc/dialects/sql_server.md
  doc/dialects/sybase.md
  doc/dialects/teradata.md
  pom.xml
  src/main/java/com/exasol/adapter/dialects/hive/HiveSqlGenerationVisitor.java
  src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitor.java
  src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitor.java
  src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
  src/test/java/com/exasol/adapter/dialects/db2/DB2SqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/dialects/hive/HiveSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/hive/HiveSqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialectTest.java
  src/test/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialectTest.java
  src/test/java/com/exasol/adapter/dialects/sybase/SybaseSqlGenerationVisitorTest.java
  src/test/java/utils/SqlNodesCreator.java
Labels: refactoring

#399 #391: Removed the API documentation from this repository and added a …
  README.md
  doc/changes/changes_4.0.4.md
  doc/development/api/capabilities_list.md
  doc/development/api/scalar_functions_api.md
  doc/development/api/virtual_schema_api.md
  doc/development/developing-sql-dialect/developing_a_dialect.md
  doc/development/developing-sql-dialect/integration_testing.md
Labels: documentation
